spring.application.name=demo

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:testdb

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=eb7da619950d1c
spring.mail.password=01aa3a780b38a8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true